### ISSUE TITLE
Support for Symfony 7.1

### ISSUE THREAD

**Issue by rey26** [FLUX-SE/odoo-api-client#4]
We would like to use this package in our Symfony 7.1 project but we can not install it due to constraints only for LTS Symfony versions (5.4 and 6.4)

**Comment by Prometee** [comment]
Hello @rey26, it should be easy to support it, I guess only the serializer interfaces have changed.
Are you able to make a PR about it ?

**Comment by rey26** [comment]
Yes, I have already created a new branch locally and committed the changes, but I'm not able to push to repository and make a PR. Will you be able to grant me such access, please?

**Comment by Prometee** [comment]
@rey26 unfortunatly it's not how it works, you have to:

- fork this repository into your github account
- clone the forked repository locally
- create a new branch
- commit your change and push them
- get back on this repository and click on the "Pull requests" tab
- a notification must be there to help you create your PR

**Comment by rey26** [comment]
@Prometee Thanks, it's the first time for me. The PR is ready.
